/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./src/components/Chart/Chart.vue')['default']
    DialogMap: typeof import('./src/components/Dialog/DialogMap.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    IndicatorMenu: typeof import('./src/components/Indicator/IndicatorMenu.vue')['default']
    Map: typeof import('./src/components/Map/Map.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar/Sidebar.vue')['default']
    SidebarAbout: typeof import('./src/components/Sidebar/SidebarAbout.vue')['default']
    SidebarBiology: typeof import('./src/components/Sidebar/SidebarBiology.vue')['default']
    SidebarChemisty: typeof import('./src/components/Sidebar/SidebarChemisty.vue')['default']
    SidebarMenu: typeof import('./src/components/Sidebar/SidebarMenu.vue')['default']
    SidebarPage: typeof import('./src/components/Sidebar/SidebarPage.vue')['default']
    Slider: typeof import('./src/components/Slider/Slider.vue')['default']
  }
}
